### ISSUE TITLE
Musthaves

### ISSUE THREAD

**Issue by FerrumBrain** [khbminus/CppTickets#26]
@Taifin 
- **base_structure_c_cpp.md**
"/ - целочисленное деление" - неправда, оно может быть и обычным, если делимое или делитель дробные
- **classes.md**
"Если хотим для Derived добавить конструктор, то в нём обязаны сконструировать базовый класс." - если ничего не конструировать в явном виде, вызовется конструктор по умолчанию, это стоит отметить
- **const_correctness.md**
"Const-qualifier у методов" - стоит добавить(потому что это звучит как 100% то, что спросят, если не упомянуть), что если же метод, помеченный константным, меняет объект это ошибка компиляции(не УБ)
 - **polymorphic.md**
"virtual type func() const = 0 - чисто виртуальная функция, которую обязательно нужно переопределить в каком-то из наследников." - необязательно. Если в наследнике не переопределена какая-либо чисто виртуальная функция родителя, он получает копию этой же функции и она тоже чисто виртуальная, то есть дочерний класс тоже абстрактный

**Comment by Taifin** [comment]
Про вещественное деление там кажется снизу прям написано, что если операнд вещественный, `/` - тоже, остальное кк
