### ISSUE TITLE
Замечания по билету 17

### ISSUE THREAD

**Issue by das747** [khbminus/CppTickets#29]
Зачем-то две одинаковые строчки, возможно там должен был быть знак >
https://github.com/khbminus/CppTickets/blob/8aa3590ebcbb96ff02cd5ea36c84cd79794ac8b3/tickets/ticket17.md?plain=1#L468

Кажется тут * не там стоит, так мы получаем первый символ строки
https://github.com/khbminus/CppTickets/blob/dfb44fd1ff24428a1094a0224c2e780f74e7dba6/tickets/ticket17.md?plain=1#L503

include
https://github.com/khbminus/CppTickets/blob/dfb44fd1ff24428a1094a0224c2e780f74e7dba6/tickets/ticket17.md?plain=1#L575

**Comment by kholkinilya** [comment]
Fixed
