### ISSUE TITLE
masthaves

### ISSUE THREAD

**Issue by jegorpopow** [khbminus/CppTickets#31]
@Taifin 

* `c.md` Кавычки у строковых литералов

**Comment by jegorpopow** [comment]
typename - плохое название для типа в примерах, т.к. зарезервировано

**Comment by jegorpopow** [comment]
Виртуальные методы создаются с помощью ключевого слова virtual и могут перезаписываться наследниками с помощью слова override (virtual наследнику добавлять необязательно). Всегда вызывается виртуальная функция, принадлежащая тому классу, от которого мы вызвались.

override - не более чем проверка, что метод что-то виртуальное перезаписывает

**Comment by Taifin** [comment]
Fixed
