### ISSUE TITLE
Билет 23

### ISSUE THREAD

**Issue by waleko** [khbminus/CppTickets#33]
@FerrumBrain

https://github.com/khbminus/CppTickets/blob/a3f3929551d7948c023c416b6b75cf17b00c7799/tickets/ticket23.md?plain=1#L260

Кажется, `a + b` не равно `a.operator+(b)`, потому что `a + b` может так раз вызываться через друзей и проходить conversion:

```c++
#include <iostream>

struct bigint {
    bigint(int) {}
    friend bigint operator+(const bigint&, const bigint&) {return 1;}
};

int main() {
    int lhs = 3;
    bigint a = lhs + bigint(3);  // ok
    bigint b = lhs.operator+(bigint(3));  // CE
}
```

**Comment by FerrumBrain** [comment]
fixed

**Comment by waleko** [comment]
solved by #35
